runtime: nodejs22
instance_class: F1
env: standard

entrypoint: npm start

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

includes:
  - env_vars.yaml
handlers:
  # Send EVERYTHING to the Node.js entrypoint.
  # Express will now handle the JS, CSS, and the 41MB video.
  - url: /.*
    script: auto
